# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: perks_development
  username: postgres
  password:
  host: localhost
  port: 5432

test:
  <<: *default
  database: perks_test
  username: postgres
  password:
  host: localhost
  port: 5432

staging:
  <<: *default
