# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67d704f5cb1fbe5c9df8b72494bf5c290453a8e8db17e34f4ae324af1c7955884c7fbda2d2a5a18f2902524719ae07ed00029a3636eefd10abc3c19ef566dc5a

test:
  secret_key_base: a8bcab0ed9d955bda8e1e7a15278db3f01ec169f09624b6ef8bf31b57d745723f6827107bc3340d776376e4350c2fdc6fc07329838be1f4b70921dd30c709e61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
