object @employee
attributes :id,
           :employee_id,
           :first_name,
           :last_name,
           :title,
           :department,
           :salary_range,
           :email_address,
           :dob_month,
           :dob_day,
           :dob_year,
           :street_address_1,
           :street_address_2,
           :city,
           :state,
           :country,
           :phone_number
